"use strict";
const TYPES=[
 {name:"草ブロック",base:"#a55b2c",accent:"#64cf32",grass:true},{name:"原木",base:"#8f5420",accent:"#d49a48",wood:true},{name:"丸石",base:"#8c9398",accent:"#c1c5c6"},{name:"石炭鉱石",base:"#93999d",accent:"#25272a"},{name:"鉄鉱石",base:"#969b9d",accent:"#e3a17f"},{name:"金鉱石",base:"#8d9291",accent:"#ffd128"},{name:"レッドストーン鉱石",base:"#858a8b",accent:"#f12a24"},{name:"ラピス鉱石",base:"#838a8d",accent:"#245be3"},{name:"ダイヤモンド鉱石",base:"#7f898a",accent:"#27dfe3"},{name:"エメラルド鉱石",base:"#818989",accent:"#24c54a"},{name:"ネザライトブロック",base:"#332b38",accent:"#66516c"}
];
const canvas=document.querySelector("#gameCanvas"),ctx=canvas.getContext("2d"),box=document.querySelector("#gameBox");
const RANKING_API_URL="https://tqeplwfkhhcdzxxczkxu.supabase.co/rest/v1/scores",RANKING_API_KEY="sb_publishable_l4xNm-mEvxiHnuQNAXs7IA_Oh6xjsP3";
const scoreEl=document.querySelector("#score"),bestEl=document.querySelector("#best"),mobileScore=document.querySelector("#mobileScore");
let W=600,H=700,dpr=1,blocks=[],score=0,best=Number(localStorage.getItem("blockMergeBest")||0),running=false,paused=false,current=0,next=1,aimX=300,last=0,dropLock=0,overTimer=0,particles=[],scoreSaved=false,rankingResume=false;
const radii=[24,30,37,45,53,62,72,83,95,108,122];
const spriteSheet=new Image();
spriteSheet.src="block-sprites.png?v=4";
function seeded(i,j){return ((i*47+j*91+17)%100)/100}
function drawBlock(c,x,y,size,type,rotation=0,face=true){const t=TYPES[type],s=size;c.save();c.translate(x,y);c.rotate(rotation);const r=s*.2;c.shadowColor="#0005";c.shadowBlur=s*.09;c.shadowOffsetY=s*.06;c.beginPath();c.roundRect(-s/2,-s/2,s,s,r);c.fillStyle=t.base;c.fill();c.shadowColor="transparent";c.clip();if(t.grass){c.fillStyle=t.accent;c.fillRect(-s/2,-s/2,s,s*.28);for(let i=0;i<7;i++)c.fillRect(-s/2+i*s/7,-s*.23+(i%3)*s*.04,s/7,s*.08)}else if(t.wood){c.fillStyle=t.accent;c.fillRect(-s/2,-s/2,s,s*.16);c.strokeStyle="#774515";c.lineWidth=s*.035;c.strokeRect(-s*.3,-s*.46,s*.6,s*.08);for(let i=0;i<7;i++){c.fillStyle=i%2?t.accent:"#6f3e17";c.fillRect(-s/2+i*s/7,-s*.32,s/12,s*.82)}}else{for(let i=0;i<13;i++){const px=(seeded(type,i)-.5)*s*.85,py=(seeded(i,type+3)-.5)*s*.82,sz=s*(.06+seeded(i+4,type)*.08);c.fillStyle=i%3===0?t.accent:lighten(t.base,i%2?18:-12);c.fillRect(px,py,sz,sz)}}c.fillStyle="#fff4";c.beginPath();c.ellipse(-s*.18,-s*.34,s*.22,s*.055,-.15,0,Math.PI*2);c.fill();c.restore();c.save();c.translate(x,y);c.rotate(rotation);c.strokeStyle="#48250ccc";c.lineWidth=Math.max(1.5,s*.035);c.beginPath();c.roundRect(-s/2,-s/2,s,s,r);c.stroke();if(face&&s>18){const eyeY=s*.08,eyeR=s*.075;c.fillStyle="#28140c";c.beginPath();c.arc(-s*.17,eyeY,eyeR,0,Math.PI*2);c.arc(s*.17,eyeY,eyeR,0,Math.PI*2);c.fill();c.fillStyle="#fff";c.beginPath();c.arc(-s*.19,eyeY-s*.025,eyeR*.36,0,Math.PI*2);c.arc(s*.15,eyeY-s*.025,eyeR*.36,0,Math.PI*2);c.fill();c.strokeStyle="#28140c";c.lineCap="round";c.lineWidth=Math.max(1.4,s*.027);c.beginPath();c.arc(0,s*.1,s*.105,.12,Math.PI-.12);c.stroke();c.fillStyle="#ff82a0";c.beginPath();c.ellipse(-s*.3,s*.18,s*.095,s*.052,0,0,Math.PI*2);c.ellipse(s*.3,s*.18,s*.095,s*.052,0,0,Math.PI*2);c.fill()}c.restore()}
function lighten(hex,n){const v=parseInt(hex.slice(1),16),r=Math.max(0,Math.min(255,(v>>16)+n)),g=Math.max(0,Math.min(255,((v>>8)&255)+n)),b=Math.max(0,Math.min(255,(v&255)+n));return `rgb(${r},${g},${b})`}
function drawSpriteBlock(c,x,y,size,type,rotation=0){if(!spriteSheet.complete||!spriteSheet.naturalWidth){drawBlock(c,x,y,size,type,rotation,true);return}const cols=4,rows=3,spriteIndex=type+1,sw=spriteSheet.naturalWidth/cols,sh=spriteSheet.naturalHeight/rows,sx=(spriteIndex%cols)*sw,sy=Math.floor(spriteIndex/cols)*sh,d=size*1.16;c.save();c.translate(x,y);c.rotate(rotation);c.shadowColor="#0005";c.shadowBlur=size*.075;c.shadowOffsetY=size*.045;c.drawImage(spriteSheet,sx,sy,sw,sh,-d/2,-d/2,d,d);c.restore()}
function syncAim(){document.querySelector(".center-stage").style.setProperty("--aim-x",`${aimX}px`)}
function resize(){const r=box.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);aimX=Math.max(30,Math.min(W-30,aimX||W/2));syncAim()}
function makeBlock(type,x,y){const r=Math.min(radii[type]*(W/600),W*.2);return{type,x,y,r,vx:0,vy:0,angle:0,va:(Math.random()-.5)*1.2,age:0,merge:0}}
function drop(){if(!running||paused||performance.now()<dropLock)return;blocks.push(makeBlock(current,aimX,30));current=next;next=Math.floor(Math.random()*Math.min(4,2+Math.floor(score/900)));dropLock=performance.now()+480;drawPreviews()}
function update(dt){if(!running||paused)return;for(const b of blocks){b.age+=dt;b.vy+=1050*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;b.va+=(-b.angle*42-b.va*7.5)*dt;b.angle=Math.max(-.14,Math.min(.14,b.angle+b.va*dt));if(Math.abs(b.angle)<.0005&&Math.abs(b.va)<.004){b.angle=0;b.va=0}if(b.x-b.r<0){b.x=b.r;b.vx=Math.abs(b.vx)*.18;b.va+=.55}if(b.x+b.r>W){b.x=W-b.r;b.vx=-Math.abs(b.vx)*.18;b.va-=.55}const floor=H-H*.12;if(b.y+b.r>floor){const impact=b.vy;b.y=floor-b.r;b.vy=0;b.vx*=.82;if(impact>90)b.va+=(Math.random()-.5)*Math.min(2.2,impact*.007)}}
 for(let pass=0;pass<5;pass++)for(let i=0;i<blocks.length;i++)for(let j=i+1;j<blocks.length;j++){const a=blocks[i],b=blocks[j],dx=b.x-a.x,dy=b.y-a.y,overX=a.r+b.r-Math.abs(dx),overY=a.r+b.r-Math.abs(dy);if(overX>0&&overY>0){if(a.type===b.type&&a.type<TYPES.length-1&&a.age>.12&&b.age>.12){merge(i,j);i=-1;break}if(overY<=overX){const impact=Math.abs(a.vy-b.vy),dir=dy>=0?1:-1;a.y-=dir*overY*.5;b.y+=dir*overY*.5;const avg=(a.vy+b.vy)*.08;a.vy=avg;b.vy=avg;if(impact>45){const wobble=Math.min(1.5,impact*.005)*(dx>=0?1:-1);a.va-=wobble;b.va+=wobble}}else{const dir=dx>=0?1:-1;a.x-=dir*overX*.5;b.x+=dir*overX*.5;const avg=(a.vx+b.vx)*.12;a.vx=avg;b.vx=avg}}}
 const danger=H*.11;let high=false;for(const b of blocks)if(b.age>2&&b.y-b.r<danger)high=true;overTimer=high?overTimer+dt:Math.max(0,overTimer-dt*2);if(overTimer>2.2)gameOver()}
function merge(i,j){const a=blocks[i],b=blocks[j],type=a.type+1,x=(a.x+b.x)/2,y=(a.y+b.y)/2,n=makeBlock(type,x,y);n.vx=(a.vx+b.vx)/2;n.vy=Math.min(-90,(a.vy+b.vy)/3);blocks.splice(j,1);blocks.splice(i,1);blocks.push(n);score+=Math.pow(2,type)*10;updateScore();for(let k=0;k<12;k++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:(Math.random()-.8)*180,life:.7,color:TYPES[type].accent})}
function draw(){ctx.clearRect(0,0,W,H);ctx.save();ctx.strokeStyle="#fff";ctx.lineWidth=3;ctx.setLineDash([9,10]);ctx.globalAlpha=.75;ctx.beginPath();ctx.moveTo(aimX,0);ctx.lineTo(aimX,H*.23);ctx.stroke();ctx.restore();for(const b of blocks)drawSpriteBlock(ctx,b.x,b.y,b.r*2.08,b.type,b.angle);for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/.7);ctx.fillStyle=p.color;ctx.fillRect(p.x-3,p.y-3,6,6)}ctx.globalAlpha=1}
function tick(t){const dt=Math.min(.025,(t-last)/1000||.016);last=t;if(running&&!paused){update(dt);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=300*dt;p.life-=dt}particles=particles.filter(p=>p.life>0)}draw();requestAnimationFrame(tick)}
function updateScore(){const s=String(score).padStart(4,"0");scoreEl.textContent=s;mobileScore.textContent=score;if(score>best){best=score;localStorage.setItem("blockMergeBest",best)}bestEl.textContent=String(best).padStart(4,"0")}
function safeText(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function getRanking(){const response=await fetch(`${RANKING_API_URL}?select=name,score&order=score.desc,created_at.asc&limit=100`,{headers:{apikey:RANKING_API_KEY,Authorization:`Bearer ${RANKING_API_KEY}`}});if(!response.ok)throw new Error("ランキングを読み込めませんでした");return response.json()}
async function renderRanking(){const list=document.querySelector("#rankingList");list.innerHTML='<li class="ranking-empty">読み込み中...</li>';try{const ranking=await getRanking();list.innerHTML=ranking.length?ranking.map((r,i)=>`<li><span>${i+1}</span><span>${safeText(r.name)}</span><span class="rank-score">${String(r.score).padStart(4,"0")}</span></li>`).join(""):'<li class="ranking-empty">まだ記録がありません</li>'}catch(error){list.innerHTML=`<li class="ranking-empty">${safeText(error.message)}<br><small>少し待ってからもう一度ためしてね</small></li>`}}
function openRanking(){rankingResume=running&&!paused;paused=true;document.querySelector("#rankingOverlay").classList.add("active");renderRanking()}
function closeRanking(){document.querySelector("#rankingOverlay").classList.remove("active");if(rankingResume&&running)paused=false;rankingResume=false}
async function saveRanking(){if(scoreSaved)return;const input=document.querySelector("#playerName"),button=document.querySelector("#saveScoreButton"),name=(input.value.trim()||"PLAYER").slice(0,8).toUpperCase();button.disabled=true;button.textContent="登録中...";try{const response=await fetch(RANKING_API_URL,{method:"POST",headers:{apikey:RANKING_API_KEY,Authorization:`Bearer ${RANKING_API_KEY}`,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({name,score:Math.max(0,Math.floor(score))})});if(!response.ok)throw new Error("登録できませんでした");scoreSaved=true;document.querySelector("#gameOverOverlay").classList.remove("active");openRanking()}catch(error){button.textContent="もう一度ためす";button.disabled=false;alert(`${error.message}。通信を確認してね。`)}}
function drawMini(target,type){const c=target.getContext("2d");c.clearRect(0,0,target.width,target.height);drawSpriteBlock(c,target.width/2,target.height/2,Math.min(target.width,target.height)*.74,type,0)}
function drawPreviews(){drawMini(document.querySelector("#currentCanvas"),current);drawMini(document.querySelector("#nextCanvas"),next)}
function buildOrder(){const ol=document.querySelector("#blockOrder");TYPES.forEach((t,i)=>{const li=document.createElement("li"),cv=document.createElement("canvas");cv.width=cv.height=70;li.innerHTML=`<span class="num">${i+1}</span>`;li.append(cv);li.insertAdjacentHTML("beforeend",`<span>${t.name}</span>`);ol.append(li);drawMini(cv,i)})}
function start(){blocks=[];particles=[];score=0;overTimer=0;current=0;next=1;running=true;paused=false;scoreSaved=false;const saveButton=document.querySelector("#saveScoreButton");saveButton.disabled=false;saveButton.textContent="ランキング登録";updateScore();drawPreviews();document.querySelectorAll(".overlay").forEach(x=>x.classList.remove("active"))}
function gameOver(){running=false;scoreSaved=false;document.querySelector("#finalScore").textContent=score;document.querySelector("#gameOverOverlay").classList.add("active")}
function togglePause(force){if(!running)return;paused=force===undefined?!paused:force;document.querySelector("#pauseOverlay").classList.toggle("active",paused)}
canvas.addEventListener("pointermove",e=>{const r=canvas.getBoundingClientRect();aimX=Math.max(25,Math.min(W-25,e.clientX-r.left));syncAim()});canvas.addEventListener("pointerdown",e=>{e.preventDefault();const r=canvas.getBoundingClientRect();aimX=Math.max(25,Math.min(W-25,e.clientX-r.left));syncAim();drop()});document.querySelector("#startButton").onclick=start;document.querySelector("#retryButton").onclick=start;document.querySelector("#saveScoreButton").onclick=saveRanking;document.querySelector("#closeRankingButton").onclick=closeRanking;document.querySelector("#resumeButton").onclick=()=>togglePause(false);document.querySelector("#restartFromPause").onclick=start;document.querySelectorAll("[data-pause]").forEach(b=>b.onclick=()=>togglePause());document.querySelectorAll("[data-ranking]").forEach(b=>b.onclick=openRanking);window.addEventListener("resize",resize);document.addEventListener("visibilitychange",()=>{if(document.hidden&&running&&!paused)togglePause(true)});buildOrder();renderRanking();resize();updateScore();drawPreviews();requestAnimationFrame(tick);
